name: A workflow for building basic PLT test image
on: push

jobs:
  build:
    name:  Build PLT-300
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/build
      - name: Upload Release
        uses: meeDamian/github-release@2.0
        if: contains(github.ref, 'tags')
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          files: dist/*
          gzip: false
